# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('member', '0002_myuser_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mybook',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
