# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=200)),
                ('cover_thumbnail', models.URLField()),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('google_id', models.CharField(max_length=100)),
            ],
        ),
    ]
