# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20170414_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.MyBook')),
            ],
        ),
    ]
