# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_mybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
