# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_mybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('mybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.MyBook')),
            ],
        ),
    ]
