# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='mybook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='book.MyBook'),
        ),
    ]
