# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170414_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='mybook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.MyBook'),
        ),
    ]
