# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170411_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstar',
            name='content',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
