# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_auto_20170411_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstar',
            name='mybook',
        ),
        migrations.AddField(
            model_name='bookstar',
            name='book',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstar',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
