# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20170412_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstar',
            name='mybook',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='book.MyBook'),
            preserve_default=False,
        ),
    ]
