# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20170415_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='bookstar',
            old_name='rating',
            new_name='content',
        ),
    ]
