# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_bookstar_mybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstar',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookstar',
            name='user',
        ),
    ]
