# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20170415_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstar',
            old_name='created_date',
            new_name='updated_date',
        ),
    ]
