# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_bookstar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstar',
            name='user',
        ),
    ]
