# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170412_1444'),
        ('book', '0016_remove_bookstar_user'),
    ]

    operations = [
    ]
